export default defineConfigWithTheme<ThemeConfig>({
  //...

  // 生成站点地图
  sitemap: {
    hostname: 'https://vitepress-theme-bluearchive.vercel.app', //替换为你自己的域名
  },

  // 站点标题配置
  title: "Sensei's 部落格",
  description: "Sensei's 部落格",

  themeConfig: {
    //banner区配置
    videoBanner: false, //是否显示视频背景
    name: "Sensei's 部落格", //首页标题
    welcomeText: 'Hello, VitePress', //首页欢迎语
    motto: ['和你的日常，就是奇迹', '何気ない日常で、ほんの少しの奇跡を見つける物語。'], //首页motto
    social: [ //社交链接配置(netease_music,coolapk,reddit)
      { icon: 'github', url: 'https://github.com/' },
      { icon: 'bilibili', url: 'https://www.bilibili.com/' },
      { icon: 'qq', url: 'https://im.qq.com/index/' },
      { icon: 'wechat', url: 'https://weixin.qq.com/' },
    ],

    //spine语音配置，可选zh/jp
    spineVoiceLang: 'jp',

    //footer配置
    footerName: 'Sensei',
    poweredList: [
      { name: 'VitePress', url: 'https://github.com/vuejs/vitepress' },
      { name: 'GitHub Pages', url: 'https://docs.github.com/zh/pages' },
    ],

    //gitalk配置
    clientID: 'YourClientID',
    clientSecret: 'YourClientSecret',
    repo: 'YourRepoName',
    owner: 'YourGitHubName',
    admin: ['YourGitHubName'],
  }
}),
